### ISSUE TITLE
Need Help: Unable to pass npm test because of icon.

### ISSUE THREAD

**Issue by ngudbhav** [electron/apps#972]
![256x256](https://user-images.githubusercontent.com/31446376/52842201-5e2b7200-3124-11e9-8758-8d3cf38f62e1.png)
I want to use the above app icon. npm test fails with the following error:

Am I missing something to consider? Thanks in advance.

The github repo link is <a href="https://github.com/ngudbhav/TriCo-electron-app">this</a>.
```D:\NGUdbhav\NGUdbhav Works\Electron\electron-apps>npm test

> electron-apps@1.7367.0 test D:\NGUdbhav\NGUdbhav Works\Electron\electron-apps
> mocha --reporter min test/human-data.js test/colors-spec.js && standard --fix
  13782 passing (10s)
  1 failing
1) colors
       should skip entries whose icons are unreadable:
      AssertionError: expected { Object (white, black) } to have key 'black'
      + expected - actual
       [
         "black"
      -  "white"
       ]
      at Context.it (test\colors-spec.js:118:13)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! Test failed.  See above for more details.```

**Comment by ngudbhav** [comment]
It seems the issue was with my local system. The same test when uploaded to travis succeeded.
